branches:
  only:
  - master
  - "/^v0.*$/"
language: python
python:
- '3.6'
services:
- docker
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- docker-compose build
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -c 'create database "just-spaces";' -U postgres
- psql -U postgres -d travis -c "create extension postgis"
- mv justspaces/local_settings.example.py justspaces/local_settings.py
script:
- python manage.py migrate
- pytest
- docker-compose run --rm frontend lint
- docker-compose run --rm frontend test
notifications:
  slack:
    secure: tmPcowFRreC/+uLw9ebUVeTattyhcpftyRLNbaP3x30+oaa/UaoXs8traBWZTh9g1CAQqgOxgRMrQCzk4dAM3QWk1ZwfVYM8xHn7YAfhvUgYIycz2eqxYh95iTj2q1fGhiURzJMyHHCdDJkIwKvEt3j56mBEm9nuyMSgkpOiDJhSb4eUeUF4OJ3kDazpQOmP+0T9va/Z3ukAVkaQEsF/mt8ZfqLHwRTQEb4fuzFlMjt78hspD9qo0cPlt5ugj2Ew5RCZlhOyHP6wgWJA97fDyAjyG+zGbx3A0iCeQUTqMUl6BVwmjxQUOW+1spXsbsfxaMG+e2dVGjt5TWTTDSqospesA8wmrqjcDSHc6zhytsW/NAu82PlPK5DDz6InBq3/BvRU2mFE3kMcc7mikFfhRXjY+ZY6EUnjCcuG2zBSQFn8lmzfxO7ObKq0TVavU+QWeRk20nC9oBW/Gbm7YaoAQMbbQO6Ez03Rv9BsjtqQwVnJVkLANO8duIPvLD+vQh0PS61VwHULlMUUJwsN6iujXSKB8u0m7pKAfv+mTmNvoE/gFuubmtiqSc3a6jyjyurkv+UV8tUo7S+1DuAuc4G9iJiczmExkkUrkPMKE9djdlfqedgro8l0jinWFp70+NSkSRUy9SD9n0eF1eZbIYBgS8xjiqKqIrWlnWusYh/oCoU=
deploy:
  provider: codedeploy
  access_key_id: AKIAJNYGDLOJKHOUWCAA
  secret_access_key:
    secure: sRKWoVSKeDFABEHSKBVEZHZ7h+tW8rbKcNKbnIiwGFG6+2tg5iMI//XPZ1ttFkEkTl9eEOcs6ZJ4meFq6f7Ky9mNFNQLIFGswpCihkkly3d0ry5jgBF2JLYpRsaKS+RB0o7i2NhRVfcGATSa02katTZsHxzV6bL+WVwMIBHdgOmsANR2A36FEDOYY09ee0vKdXKIaFvQg6FM/eb1QHrtbQ72D9y6eTaHtLrowzF41sdIfA2yx3aL7ZxHytfeSkr93nY6zycT6Y5B/Q72wRT91rHcGhA03A0IJdPJMBIDDU6bITg1MfyJTmonXIrSZQrDQjYSVcy2Eaj/UecOqHFHdGbMddTIq9ILWBewXWDqD0Yv2JeeXw5QmT6npIek/brxpe9H1SPeHgINXWu0sKEdmXbjGnH5Wm82TxIzNzDd5TzuoF5OEN+DW+QbFZYZ+wHYhPcG8hQ6TZylIH97kN+5KCFKAIZ4QSFFqc9TgbrnAIr4Na46PlmyUEioeN3hy4AUp/e25iHQvI+eYqX9SahQM/grjKT3EotdyyRLHn56lF9MptTLuHroIFMRMjrmBs3TMClb2E0oNQHZ8x7e/oOjLxfthGOAPqvBpGJ+dbRiTUFZQ7SouquaX4mVw/NGNqTg3ZTVPXwObEj4/ur4alCXaVzF+eCvDjLOqOEQdxulG3s=
  application: just-spaces
  deployment_group: staging
  on:
    repo: datamade/just-spaces
    branch: master
