branches:
  only:
  - master
  - "/^v0.*$/"
language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install -r requirements.txt
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -c 'create database "just-spaces";' -U postgres
- psql -U postgres -d travis -c "create extension postgis"
- mv justspaces/local_settings.example.py justspaces/local_settings.py
script:
- python manage.py migrate
notifications:
  webhooks:
  - https://semabot.datamade.us/travis/
deploy:
  provider: codedeploy
  access_key_id: AKIAJNYGDLOJKHOUWCAA
  secret_access_key:
    secure: oSyi9eUOny6wPZuI99JEqEHFFerUrmkRPpHknkFsMmwPboEES6AZGg8lPAZtXcqa3NXqtuAsfwMm51kVAVzFKbHMCviG5U/YiB1z3KFXKX9V+TD2+gED+m7h2F7hmZsvKH0DB+dyaKrwlQMbVtkcSuz3fSgz0TgDBUxaYvl0v81dP6dJzNVccUO70Rya50IYgkfGEyKByB3U6NF0s2KQ22odfDFpI1lg/lGjo5GhQgl+JQ8TpUaywZGYVZaaoZRjdS/fTWxjS2ViNpdrDGjAaGLEXkBEuQDxRG9T3tg9OYr4AJzB5w35xMbJTJ7utPtdHtKQitxObqo6f28PxICiKF/zUQx0k4kygIwPR69uO58W85JKtBHE3ZfX3yA5TlKV4VjrbcBXV9mPLhOmzsXwAQLhMDJ5l3A1jbzY2L75rmm3iaULWis5pQAlakV4RrCQGVA174icakg4gqgQ7HFxpkTMg4clvd6n/pLNo6ZGmsIv3VUYdtt7iCgsDibZwlEOUHUYYjdZT7V9WcoMMizaMtmGAtuMCW/kBzQaRq0b5/dEPxL6SLe9NTBC1opW/H4AaAIu9dux6lW3ishZvqxBSxVrExp7D3AHnlRk02wer5KhC0SqwTJjC5OueWuav0+M0azRPSMnv0TetChTOdCK6S7WkJczD0pZ40IR3AFvOxs=
  application: just-spaces
  deployment_group: staging
  on:
    repo: datamade/just-spaces
    branch: master
