version: 0.0
os: linux
files:
 - source: /
   destination: /home/datamade/just-spaces
hooks:
 BeforeInstall:
  - location: scripts/before_install.sh
    runas: root
 ApplicationStart:
  - location: scripts/app_start.sh
    runas: root
 AfterInstall:
  - location: scripts/after_install.sh
    runas: root
