version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/local/src
      - node_modules:/usr/local/src/node_modules
    working_dir: /usr/local/src
    entrypoint: yarn
    command: start
volumes:
  node_modules: