# Generated by Django 2.1.5 on 2019-03-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justspacesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justspacesuser',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pldp.Agency'),
        ),
    ]
