"""
Django settings for justspaces project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .local_settings import *
import gettext

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'justspacesapp',

    # django-pldp
    'countries_plus',
    'languages_plus',
    'pldp',

    # fobi core
    'fobi',

    # fobi theme
    'fobi.contrib.themes.bootstrap3',
    'fobi_custom.override_bootstrap3_theme',
    'crispy_forms',

    # fobi default form field plug-ins
    'fobi.contrib.plugins.form_elements.fields.boolean',
    'fobi.contrib.plugins.form_elements.fields.checkbox_select_multiple',
    'fobi.contrib.plugins.form_elements.fields.date',
    # 'fobi.contrib.plugins.form_elements.fields.date_drop_down',
    # 'fobi.contrib.plugins.form_elements.fields.datetime',
    # 'fobi.contrib.plugins.form_elements.fields.decimal',
    # 'fobi.contrib.plugins.form_elements.fields.email',
    # 'fobi.contrib.plugins.form_elements.fields.file',
    'fobi.contrib.plugins.form_elements.fields.float',
    # 'fobi.contrib.plugins.form_elements.fields.hidden',
    # 'fobi.contrib.plugins.form_elements.fields.input',
    # 'fobi.contrib.plugins.form_elements.fields.integer',
    # 'fobi.contrib.plugins.form_elements.fields.ip_address',
    # 'fobi.contrib.plugins.form_elements.fields.null_boolean',
    # 'fobi.contrib.plugins.form_elements.fields.password',
    'fobi.contrib.plugins.form_elements.fields.radio',
    # 'fobi.contrib.plugins.form_elements.fields.regex',
    'fobi.contrib.plugins.form_elements.fields.select',
    # 'fobi.contrib.plugins.form_elements.fields.select_model_object',
    # 'fobi.contrib.plugins.form_elements.fields.select_multiple',
    # 'fobi.contrib.plugins.form_elements.fields.select_multiple_model_objects',
    # 'fobi.contrib.plugins.form_elements.fields.slug',
    'fobi.contrib.plugins.form_elements.fields.text',
    'fobi.contrib.plugins.form_elements.fields.textarea',
    'fobi.contrib.plugins.form_elements.fields.time',
    # 'fobi.contrib.plugins.form_elements.fields.url',

    # custom pldp element
    # 'fobi.contrib.plugins.form_elements.fields.pldp',

    # fobi default form element plug-ins
    # 'easy_thumbnails',  # Required by `content_image` plugin
    # 'fobi.contrib.plugins.form_elements.content.content_image',
    'fobi.contrib.plugins.form_elements.content.content_text',
    # 'fobi.contrib.plugins.form_elements.content.content_video'

    # fobi form handlers
    'fobi.contrib.plugins.form_handlers.db_store',
    # 'fobi.contrib.plugins.form_handlers.http_repost',
    # 'fobi.contrib.plugins.form_handlers.mail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'justspaces.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'fobi.context_processors.theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'justspaces.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'

FOBI_DEFAULT_THEME = 'bootstrap3'
FOBI_THEME_FOOTER_TEXT = gettext.gettext('')
