# Generated by Django 2.1.5 on 2019-04-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190304_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justspacesuser',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='justspacesuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='justspacesuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='JustSpacesUser',
        ),
    ]
