# Generated by Django 2.1.5 on 2019-04-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fobi', '0016_auto_20190326_2010'),
        ('pldp', '0006_auto_20190402_1547'),
        ('surveys', '0003_auto_20190410_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('formentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fobi.FormEntry')),
                ('published', models.BooleanField(default=False)),
            ],
            bases=('fobi.formentry',),
        ),
        migrations.CreateModel(
            name='SurveyFormIntercept',
            fields=[
                ('surveyform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.SurveyForm')),
            ],
            bases=('surveys.surveyform',),
        ),
        migrations.CreateModel(
            name='SurveyFormObservational',
            fields=[
                ('surveyform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.SurveyForm')),
            ],
            bases=('surveys.surveyform',),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pldp.Location'),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pldp.Study'),
        ),
    ]
