# Generated by Django 2.1.5 on 2019-04-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0006_auto_20190402_1547'),
        ('fobi', '0016_auto_20190326_2010'),
        ('surveys', '0004_auto_20190410_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFormEntry',
            fields=[
                ('formentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fobi.FormEntry')),
                ('published', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('intercept', 'Intercept'), ('observational', 'Observational')], default='intercept', max_length=50)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pldp.Location')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pldp.Study')),
            ],
            bases=('fobi.formentry',),
        ),
        migrations.RemoveField(
            model_name='surveyform',
            name='formentry_ptr',
        ),
        migrations.RemoveField(
            model_name='surveyform',
            name='location',
        ),
        migrations.RemoveField(
            model_name='surveyform',
            name='study',
        ),
        migrations.RemoveField(
            model_name='surveyformintercept',
            name='surveyform_ptr',
        ),
        migrations.RemoveField(
            model_name='surveyformobservational',
            name='surveyform_ptr',
        ),
        migrations.DeleteModel(
            name='SurveyForm',
        ),
        migrations.DeleteModel(
            name='SurveyFormIntercept',
        ),
        migrations.DeleteModel(
            name='SurveyFormObservational',
        ),
    ]
