# Generated by Django 2.1.5 on 2019-04-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20190410_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyFormEntry')),
            ],
        ),
    ]
