# Generated by Django 2.1.5 on 2019-05-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0016_auto_20190326_2010'),
        ('surveys', '0006_surveychart'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveychart',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fobi.FormElementEntry'),
        ),
    ]
