# Generated by Django 2.1.5 on 2019-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveychart'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveychart',
            name='primary_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
