# Generated by Django 2.1.5 on 2019-05-28 14:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveychart_primary_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fips_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CensusObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=255)),
                ('variable', models.CharField(max_length=255)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='surveychart',
            name='census_areas',
            field=models.ManyToManyField(to='surveys.CensusArea'),
        ),
    ]
