# Generated by Django 2.1.5 on 2019-05-23 19:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveychart_primary_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=255)),
                ('variable', models.CharField(max_length=255)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='surveychart',
            name='census_observations',
            field=models.ManyToManyField(to='surveys.CensusObservation'),
        ),
    ]
