# Generated by Django 2.1.5 on 2019-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20190606_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyformentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
