# Generated by Django 2.1.5 on 2019-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_surveyformentry_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
