# Generated by Django 2.1.5 on 2019-06-19 19:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_censusarea_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusBlockGroup',
            fields=[
                ('fips_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
    ]
