# Generated by Django 2.1.5 on 2019-06-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_censusblockgroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='censusobservation',
            unique_together={('fips_code', 'variable')},
        ),
    ]
