# Generated by Django 2.1.5 on 2019-06-25 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_censusobservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusarea',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='censusarea',
            name='fips_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), help_text='Select one or more Census block groups that comprise this area. Add or remove a block group by clicking on it, or remove all block groups by clicking the "Clear all" button.', size=None, verbose_name='Block Groups'),
        ),
    ]
