# Generated by Django 2.1.5 on 2019-07-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0016_auto_20190326_2010'),
        ('surveys', '0014_censusarea_is_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyformentry',
            name='survey_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_template_name', to='fobi.FormEntry'),
        ),
    ]
