# Generated by Django 2.1.10 on 2019-08-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0012_auto_20190605_0952'),
        ('surveys', '0015_surveyformentry_survey_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusarea',
            name='agency',
            field=models.ForeignKey(blank=True, default=None, help_text='Select the agency that should be able to view and edit this area. Leave this box blank if you would like this area to be available to all agencies.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pldp.Agency'),
        ),
    ]
