# Generated by Django 2.1.10 on 2019-10-31 17:15

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_census_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusregion',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(40, -75.16), srid=4326),
        ),
        migrations.AddField(
            model_name='censusregion',
            name='default_zoom',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
