# Generated by Django 2.1.10 on 2019-11-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_censusregion_zoom_and_centroid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censusregion',
            options={'ordering': ['name']},
        ),
    ]
